# Generated by Django 3.0.8 on 2020-07-18 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_remove_ticket1_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket1')),
            ],
        ),
    ]
