# Generated by Django 3.0.8 on 2020-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20200719_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priotidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EditTicket',
        ),
    ]
