# Generated by Django 3.0.8 on 2020-07-19 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0006_auto_20200719_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=600)),
                ('prioridadarea', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('resumen', models.CharField(max_length=100)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='editticket2',
            name='id_ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket3'),
        ),
        migrations.DeleteModel(
            name='Ticket2',
        ),
    ]
