# Generated by Django 3.0.8 on 2020-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=600)),
                ('priotidadarea', models.CharField(max_length=50)),
            ],
        ),
    ]
