# Generated by Django 3.0.8 on 2020-07-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket1',
            name='fecha',
        ),
    ]
