# Generated by Django 3.0.8 on 2020-07-19 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0007_auto_20200719_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket3',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
